### ISSUE TITLE
sudo not working on bosh-stemcell-3263.22-azure-hyperv-ubuntu-trusty-go_agent.tgz

### ISSUE THREAD

**Issue by ManuJacks** [cloudfoundry/os-conf-release#17]
Hi Guys,

When we add a new user and key to vms with stemcell bosh-stemcell-3263.22-azure-hyperv-ubuntu-trusty-go_agent.tgz, we are finding that sudo doesn't work.  

We've modified the user_add pre-start.sh.erb script and created a release that works for stemcell 3263.22:

  if grep -q 'bosh_sudoers' /etc/group; then
    <% if sudo %>
      usermod -G vcap,admin,bosh_sudoers <%=user%>
    <% else %>
      usermod -G admin,vcap,bosh_sshers <%=user%>
    <% end %>
  fi

Any chance you can validate this hack as the right way to go?

**Comment by cppforlife** [comment]
@ManuJacks i would recommend using user_add job from https://github.com/cloudfoundry/os-conf-release to add additional users.

**Comment by ManuJacks** [comment]
@cppforlife We can add users.  They just can't sudo without the hack mentioned above.

**Comment by dpb587-pivotal** [comment]
Make sure you're using v15+ - similar logic to what you found was added to user_add [a while back](https://github.com/cloudfoundry/os-conf-release/commit/0dcfab20697f98b8549b40c3f368a89916e626b6).

**Comment by ManuJacks** [comment]
@dpb587-pivotal and @cppforlife,

The Problem that I'm trying to resolve is that some stemcells don't actually have the bosh_sshers group.  By adding an else statement, we catch those stemcells that don't have that group.  I tested a dev release and it works.   

 if grep -q 'bosh_sshers' /etc/group; then
    <% if sudo %>
      usermod -G vcap,admin,bosh_sshers,bosh_sudoers <%=user%>
    <% else %>
      usermod -G vcap,bosh_sshers <%=user%>
    <% end %>
  else
    <% if sudo %>
      usermod -G vcap,admin,bosh_sudoers <%=user%>
    <% else %>
      usermod -G vcap <%=user%>
    <% end %>
  fi

**Comment by dpb587-pivotal** [comment]
I understand, but I think the conditional logic you're looking for is already committed in recent versions of `user_add` ([source](https://github.com/cloudfoundry/os-conf-release/blob/71f5c90f70285fdf58be85106da69e66385577fe/jobs/user_add/templates/pre-start.sh.erb#L35-L41)). Can you check the version you're using?

**Comment by ManuJacks** [comment]
@dpb587-pivotal 

We have pulled from master, to make our new release, based on the above mod to the pre-start.sh.erb file.  The extra else condition adds the users to the correct groups, if the bosh_ssher group does not exist, as is the case with the stemcell mentioned.  We have tested a few times to find the mods allow successful sudo functionality.

**Comment by pwebber1** [comment]
++ for this issue. We see the issue with stemcell 3312 bosh-vsphere-esxi-ubuntu-trusty-go_agent as well. Users are created but sudo prompts for a password. Using os-conf v19. Updating to stemcell 3468.11 resolves the issue.

**Comment by dpb587-pivotal** [comment]
Sorry, just revisiting this and I understand the issue after rereading more closely.

Since this is only an issue on older stemcells and shouldn't be a significant issue on recent environments, please feel free to make a pull request if this is still a concern.
