### ISSUE TITLE
new user_mod job

### ISSUE THREAD

**Issue by pako-grape** [cloudfoundry/os-conf-release#18]
Hi,
Using [BBR](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore) requires vcap in 'bosh_sudoers' group. When deploying bosh director it isn't, so what about adding simple user_mod job?
For example something like: https://github.com/pako-grape/os-conf-release

**Comment by dpb587-pivotal** [comment]
Hi - I think we should avoid a `user_mod` job because it introduces an expectation on existing state, when we should really be creating and maintaining the exact, purpose-specific users that we need.

However, can you clarify which `bbr` subcommand you're using and which release requires vcap to have sudo privileges? This should not be necessary and is more likely to be due to a bug in the release or improperly authenticating with `bbr`.

**Comment by pako-grape** [comment]
When trying to make director backup:
```bbr director --private-key-path bosh.pem --username vcap --host 10.92.1.6 backup```
It fails with such errors:
```
[bbr] 2017/09/04 13:11:07 INFO - Running pre-checks for backup of 10.92.1.6...
[bbr] 2017/09/04 13:11:07 INFO - Scripts found:
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/blobstore/backup
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/blobstore/restore
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/credhub/backup
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/credhub/restore
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/director/backup
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/director/restore
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/uaa/backup
[bbr] 2017/09/04 13:11:07 INFO - bosh/0/uaa/restore
[bbr] 2017/09/04 13:11:07 INFO - Starting backup of 10.92.1.6...
[bbr] 2017/09/04 13:11:07 INFO - Running pre-backup scripts...
[bbr] 2017/09/04 13:11:07 INFO - Done.
[bbr] 2017/09/04 13:11:07 INFO - Running backup scripts...
[bbr] 2017/09/04 13:11:07 INFO - Backing up blobstore on bosh/0...
[bbr] 2017/09/04 13:11:07 INFO - Done.
[bbr] 2017/09/04 13:11:07 ERROR - backup script for job blobstore failed on bosh/0.
Stdout: 
Stderr: sudo: no tty present and no askpass program specified
// there's more but similar
```
BOSH was deployed using bosh-deployment repo with credhub and uaa.

**Comment by dpb587-pivotal** [comment]
The `vcap` user intentionally does not have sudo permissions, so you cannot use it for authentication with the `bbr` tool's `director` subcommand. You'll probably want to create a dedicated user via `user_add` job that you can use with the `--username` option.

For inspiration, you may find the [`jumpbox-user.yml`](https://github.com/cloudfoundry/bosh-deployment/blob/6519304c61e683251a2eb68d39ae2eca9bf516d9/jumpbox-user.yml) ops file useful.

Give that a try, and let us know if you run into any other issues.

**Comment by pako-grape** [comment]
Ok, thanks for clarifying this.
