### ISSUE TITLE
support custom profile when user_add

### ISSUE THREAD

**Issue by aad** [cloudfoundry/os-conf-release#20]
Thanks for the work, its useful. 

We have a requirement to customise the user profile when user login, for instance forcing the user to run a command and showing user a menu to be able to run a list of pre defined tasks. Will this be considered in the roadmap, like support adding arbitrary lines/scripts into user profile?

**Comment by cppforlife** [comment]
@aad we were not planning it to use it that way, but i think we would accept a pr with this functionality.

**Comment by dpb587-pivotal** [comment]
This sounds more like restricting the user's login shell, which should be supported by using the [`shell`](https://github.com/cloudfoundry/os-conf-release/blob/cccac5483743a4d7c43208d02778a830b55b369b/jobs/user_add/spec#L28) option. Would that be sufficient for your needs?
