### ISSUE TITLE
Create user_delete job

### ISSUE THREAD

**Issue by greggha** [cloudfoundry/os-conf-release#22]
We have a use case to create a user in bosh-deployed VMs for security scanning purposes, but we want to be able to delete the user once the scan is complete. Has a user_delete job been discussed?

**Comment by dpb587-pivotal** [comment]
This is a bit interesting... typically you'd want to run a scan on any change of state (if not perpetually). But, in BOSH, changing the configuration of a VM (like adding `user_delete`) implies a change of state. So it seems little odd for security tools to ignore some state changes.

Can you be a bit more specific about your use case? Typically security scanning tools want constant access (even if they may not use it 100% of the time). Can you share what kind of security scanning software you're trying to implement? Are there reasons the software cannot be running all the time? Or can it be installed on the VM itself and run as a daemon?

In general, the `user_delete` job would imply it's negating a change made by a previous job (like `user_add`), which, at best, becomes a no-op during a deploy. For that reason alone, I don't think we'd be interested in it for this sort of use case. Feel free to share more though.

**Comment by dpb587-pivotal** [comment]
I like the release-specific user group idea.

**Comment by cppforlife** [comment]
closing this issue in favor of: https://github.com/cloudfoundry/os-conf-release/issues/31
