### ISSUE TITLE
Create ca_certs job

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry/os-conf-release#24]
Hey,

I want to add trusted certificates to a bosh, rolled out using `bosh create-env`.
I tried to achieve this using the `runtime-config` of `os-conf-release`:

The respective part of my runtime-config:

    releases:
    - name: os-conf
       version: 13
    addons:
    - name: os-configuration
      jobs:
      - name: ca_certs
        release: os-conf
        properties:
          certs: |
            -----BEGIN CERTIFICATE-----
            certificate1...
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            certificate2...
            -----END CERTIFICATE-----

I also updated the manifest to enforce a redeployment. However, it does not work. When logging in to the bosh vm, I cannot find any files in `/usr/local/share/ca-certificates/`.

What am I doing wrong?

**Comment by dpb587-pivotal** [comment]
Sorry for the delay. Currently `bosh create-env` does not support the `addons` section. You would need to include the `ca_certs` job in the main instance group definition (alongside the `director` and `nats` jobs).

Once you have your director up and running, you should be able to execute the `bosh update-runtime-config ...` command with your existing config. Then your future instances will have these CA certs installed on them.
