### ISSUE TITLE
auditd changes using os-conf-release v19

### ISSUE THREAD

**Issue by simmyxavier** [cloudfoundry/os-conf-release#25]
Looking for template sample to add additional audit parameters in audit.rules file in addition to default. For eg: Add below in /etc/audit/rules.d/audit.rules and restart auditd daemon (service auditd restart)
 
# Additional commands to be monitored
-a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/who -k privileged
-a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/whoami -k privileged
-a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/last -k privileged

**Comment by simmyxavier** [comment]
Danny – Thanks for the response. Tried to use the below setting and it is not working. The apply goes through but the audit.rules is not getting updated with the addional rules required. Below are my files and settings in bosh. Do I need to do anything additional to be done to make this working?

Sorry newuser to github and not familiar enough – what you mean by “Interested in making a pull request for this?”

ubuntu@bosh-stemcell:~$ cat os-conf-add-on.yml
releases:
- { name: os-conf, version: "19" }
addons:
- name: os-configuration
  jobs:
  - name: auditd
    release: os-conf
  properties:
    immutable: true # default
    rules:
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/who -k privileged
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/whoami -k privileged
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/last -k privileged
ubuntu@bosh-stemcell:~$

ubuntu@bosh-stemcell:~$ bosh2 -e phx-tst runtime-config
Using environment '10.148.97.11' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

No runtime config

Exit code 1
ubuntu@bosh-stemcell:~$

ubuntu@bosh-stemcell:~$ bosh2 -e phx-tst update-runtime-config os-conf-add-on.yml
Using environment '10.148.97.11' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

+ releases:
+ - name: os-conf
+   version: '19'

+ addons:
+ - jobs:
+   - name: auditd
+     release: os-conf
+   name: os-configuration
+   properties:
+     immutable: "<redacted>"
+     rules:
+     - "<redacted>"
+     - "<redacted>"
+     - "<redacted>"

Continue? [yN]: y

Succeeded
ubuntu@bosh-stemcell:~$ bosh2 -e phx-tst runtime-config
Using environment '10.148.97.11' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

addons:
- jobs:
  - name: auditd
    release: os-conf
  name: os-configuration
  properties:
    immutable: true
    rules:
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/who
      -k privileged
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/whoami
      -k privileged
    - -a always,exit -F perm=x -F auid>=500 -F auid!=4294967295 -F path=/usr/bin/last
      -k privileged
releases:
- name: os-conf
  version: "19"

Succeeded
ubuntu@bosh-stemcell:~$



Thanks
Simmy

**Comment by dpb587-pivotal** [comment]
Hi - this functionality does not currently exist in this release. Our team probably will not have time to implement this in the near future.

If you're motivated for this functionality, please feel free to work on this. The snippet in my last comment would probably be a good interface, if you want to implement it to that spec; then we'd be able to receive and review your pull request of changes.

Feel free to propose alternative implementations, if you have other ideas on the interface.
