### ISSUE TITLE
enhancement to add `resolv.conf` options set

### ISSUE THREAD

**Issue by ssurenr** [cloudfoundry/os-conf-release#26]
Either modify search_domain job or create a new job to modify `resolv.conf` options set such as timeout, rotate, etc. 
Ref: https://www.freebsd.org/cgi/man.cgi?query=resolv.conf&manpath=SuSE+Linux/i386+11.3

**Comment by cppforlife** [comment]
@ssurenr i would be open to a PR to add `resolv` job that supersedes `search_domain` job and exposes other options. btw some of the options are not necessary if bosh-dns is in use (soon to be default for bosh installations). bosh-dns for example rotates and randomly chooses recursors.

**Comment by ssurenr** [comment]
The purpose of this proposal is to contain the impact of a DNS Sever failure regardless whether it is in-house DNS or Bosh DNS. I would love to submit a PR but need some technical help.

**Comment by dpb587-pivotal** [comment]
@ssurenr feel free to use the referenced [search_domain](https://github.com/cloudfoundry/os-conf-release/tree/master/jobs/search_domain) job as a basis for your change to add a new `resolv` job. Once you have had a chance to test your release with the new job, we'll be able to review your pull request. Thanks.
