### ISSUE TITLE
Issue creating 'home' directory.

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry/os-conf-release#28]
On https://github.com/cloudfoundry/os-conf-release/blob/master/jobs/user_add/templates/pre-start.sh.erb#L35

This works with release 15 but breaks with release 19

The command `getent passwd <%=user%> > /dev/null || useradd --create-home <%=user%> --base-dir "$home_dir"` actually results in the following error:

`+ home_dir=/home
+ getent passwd backup
+ chown -R backup: /home/backup
chown: cannot access '/home/backup': No such file or directory
`
Fails as well with persistent disk.

Should be:
`getent passwd <%=user%> || useradd --create-home <%=user%> --base-dir "$home_dir"`

**Comment by keithkroeger** [comment]
Please disregard and close.

**Comment by bruxelles86** [comment]
We've hit this as well. What was your solution out of interest?

**Comment by bruxelles86** [comment]
Hah. Figured it out. Our mistake was to deploy first with `persistent_homes: true`, and then try with that set to `false`. A `bosh recreate` fixed everything.
