### ISSUE TITLE
/etc/hosts

### ISSUE THREAD

**Issue by lcacciagioni** [cloudfoundry/os-conf-release#3]
Is it possible to add a job to edit the /etc/hosts file?

**Comment by dpb587-pivotal** [comment]
While technically a job could edit the `/etc/hosts` file, that file is currently managed by BOSH agent and can be overwritten without notice. A better option may be to integrate with [bosh-dns](http://bosh.io/docs/dns) using aliases or handles. Closing for now, but feel free to join us on Slack in [cloudfoundry#bosh](https://slack.cloudfoundry.org/) to continue a discussion about what you're looking for.
