### ISSUE TITLE
update user_add job to use linux user group to determine which users to delete upon an update

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/os-conf-release#31]
related conversation: https://github.com/cloudfoundry/os-conf-release/issues/22

cannot use bosh_sshers as we do not control it; however, we can make a new group `os-conf-users` ?

**Comment by CAFxX** [comment]
AFAIK this does not solve the problem that the group (and, therefore, the users) won't be deleted if the user_add job (or os-conf-release) is removed from the instance group without recreating the VMs.

One way would be to have the [proposed drain improvements](https://github.com/cloudfoundry/bosh-notes/pull/47/files) or to allow to specify a job as "tainting" (for lack of better word) i.e. requiring VM recreation during all deploy ops.
