### ISSUE TITLE
Please release a new version to bosh.io

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/os-conf-release#35]
Hi, it's been about 4 months since a final version was published for this release. I would like to stop maintaining a fork that contains merged changes.

Could you please cut a new final.

Thanks!

CC @Callisto13

**Comment by dpb587-pivotal** [comment]
Huh, I guess it has been a while. Thanks for the reminder! I've created [Story #159169573](https://www.pivotaltracker.com/story/show/159169573) for us to discuss and prioritize.

**Comment by mfine30** [comment]
We've cut a v20.0.0 – https://bosh.io/releases/github.com/cloudfoundry/os-conf-release. Thanks for the reminder!
