### ISSUE TITLE
user_add spec description is out of date

### ISSUE THREAD

**Issue by aoldershaw** [cloudfoundry/os-conf-release#50]
The description for the `user_add` job states: 

```
Each user should specify a `name` attribute, and one of either `crypted_password` or `public_key`
```

As of https://github.com/cloudfoundry/os-conf-release/pull/40, both fields may be specified simultaneously. The description should make it clear that this is possible.

**Comment by aashah** [comment]
Nice and simple, fixed.

thanks,
aakash
