### ISSUE TITLE
malformed release on v21.0.0 tag

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/os-conf-release#51]
On tag v21.0.0, the file releases/os-conf/os-conf-21.0.0.yml is missing

**Comment by MerricdeLauney** [comment]
Hey, thanks for catching this!

We found the root issue to be in a concourse resource we're using to manage cutting the release - https://github.com/dpb587/bosh-release-resource/issues/7

We'll manually adjust the tag for now, and fix some of the tooling.

Gonna close this issue, but feel free to re-open.

**Comment by aashah** [comment]
@poblin-orange 

Thinking about this more....and this isn't actually an issue.

Having a tag point to the commit where the final release artifacts are built is not correct. The correct thing to do (which the resource does), is have the git tag target the commit that the final release is built from.

If you are trying to look for final release artifacts, go to `master`. These artifacts don't change.

We'll probably point the tag back to the correct commit.

**Comment by poblin-orange** [comment]
ok thks :-)
