### ISSUE TITLE
Pre-stop script job not available

### ISSUE THREAD

**Issue by dimitdb** [cloudfoundry/os-conf-release#63]
I would like to add pre-stop script job, similar to https://github.com/cloudfoundry/os-conf-release/issues/56
Need to do some housekeeping before the machine stops.

The PR will follow shortly.

**Comment by C5328425** [comment]
https://github.com/cloudfoundry/os-conf-release/pull/64

**Comment by dimitdb** [comment]
Decided to use a dedicated bosh release, that includes drain job.
