### ISSUE TITLE
Missing os-conf-22.2.1.yml

### ISSUE THREAD

**Issue by JoschuaA4** [cloudfoundry/os-conf-release#68]
I have tried to upgrade our existing os-conf installation from version 22.2.0 to 22.2.1.
Since I didn't not now enough about os-conf I used the following [documentation](https://www.pivotal.my/bosh-os-conf/).
Unfortunately I did not get past the step
bosh create-release releases/os-conf/os-conf-<VERSION>.yml --tarball os-conf-<VERSION>.tgz
because the file releases/os-conf/os-conf-22.2.1.yml is not included in release 22.2.1 os-conf.
Have I made a mistake here?

**Comment by JoschuaA4** [comment]
Thank you for your advise with the pre-build release but again the v22.2.1 is missing there too.

**Comment by ramonskie** [comment]
so i see the problem now.
`22.2.1` has never been released thats also why it is not available on bosh.io
for some reason the ci did create a release tag. i will look in to it.

if for some reason you need it now i would recommend
```
git clone https://github.com/cloudfoundry/os-conf-release.git
cd os-conf-release
bosh create-release --tarball=os-conf-release.22.2.1 --version 22.2.1
```
this will create a dev release. so it won't conflict once 22.2.1 is released on bosh.io

**Comment by jpalermo** [comment]
Looks like there was a bug in the publishing automation. 22.2.1 has been published now. Thanks for the report!
